<p><!-- {{ gecko_minversion_header("36") }} --></p>

<p>A <code>Deferred</code> object is returned by the <code>PromiseUtils.defer()</code> method to provide a new promise along with methods to change its state.</p>

<h2 id="Method_overview">Method overview</h2>

<table class="standard-table">
 <tbody>
  <tr>
   <td><code>void <a href="#resolve()">resolve</a>([optional] aValue);</code></td>
  </tr>
  <tr>
   <td><code>void <a href="#reject()">reject</a>([optional] aReason);</code></td>
  </tr>
 </tbody>
</table>

<h2 id="Properties">Properties</h2>

<table class="standard-table" style="width: auto;">
 <tbody>
  <tr>
   <td class="header">Attribute</td>
   <td class="header">Type</td>
   <td class="header">Description</td>
  </tr>
  <tr>
   <td><code>promise</code> <!-- {{ReadOnlyInline()}} --></td>
   <td><!-- {{jsxref("Global_Objects/Promise", "Promise")}} --></td>
   <td>A newly created promise, initially in the pending state.</td>
  </tr>
 </tbody>
</table>

<h2 id="Methods">Methods</h2>

<h3 id="resolve()">resolve()</h3>

<p>Fulfills the associated promise with the specified value, or propagates the state of an existing promise. If the associated promise has already been resolved, either to a value, a rejection, or another promise, this method does nothing.</p>

<div class="note"><strong>Note:</strong> This function is exactly same as <!-- {{jsxref("Global_Objects/Promise", "Promise")}} --> constructor's <code>resolve</code> argument, and can be called with any value of <code>this</code>.</div>

<div class="note"><strong>Note:</strong> Calling this method with a pending promise as the <code>aValue</code> argument, and then calling it again with another value before the promise is resolved or rejected, will have no effect the second time, as the associated promise is already resolved to the pending promise value as its resolution.</div>

<pre>void resolve(
  aValue
);
</pre>

<h6 id="Parameters">Parameters</h6>

<dl>
 <dt><code>aValue</code> <!-- {{ optional_inline() }} --></dt>
 <dd>If this value is not a promise, including <code>undefined</code>, it becomes the fulfillment value of the associated promise. If this value is a promise, then the associated promise will be resolved to the passed promise, and follow the state as the provided promise (including any future transitions).</dd>
</dl>

<h3 id="reject()">reject()</h3>

<p>Rejects the associated promise with the specified reason. If the promise has already been resolved, either to a value, a rejection, or another promise, this method does nothing.</p>

<div class="note"><strong>Note:</strong> This function is exactly same as <!-- {{jsxref("Global_Objects/Promise", "Promise")}} --> constructor's <code>reject</code> argument, and can be called with any value of <code>this</code>.</div>

<pre>void reject(
  aReason
);
</pre>

<h6 id="Parameters_2">Parameters</h6>

<dl>
 <dt><code>aReason</code> <!-- {{ optional_inline() }} --></dt>
 <dd>
 <p>The rejection reason for the associated promise. Although the reason can be <code>undefined</code>, it is generally an <!-- {{jsxref("Global_Objects/Error", "Error")}} --> object, like in exception handling.</p>

 <div class="note"><strong>Note:</strong> This argument should not be a promise. Specifying a rejected promise would make the rejection reason equal to the rejected promise itself, and not its rejection reason.</div>
 </dd>
</dl>

<h2 id="See_also">See also</h2>

<ul>
 <li><a href="https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/PromiseUtils.jsm" title="PromiseUtils.jsm">PromiseUtils.jsm</a></li>
 <li><!-- {{jsxref("Global_Objects/Promise", "DOM Promise", "", 1)}} --></li>
</ul>