<div><!-- {{SpiderMonkeySidebar("JSAPI")}} --></div>
<div class="summary">
<p>Clear the currently pending exception in a context.</p>
</div>
<h2 id="Syntax" name="Syntax">Syntax</h2>
<pre class="brush: cpp">void
JS_ClearPendingException(JSContext *cx);
</pre>
<table class="fullwidth-table">
 <tbody>
  <tr>
   <th>Name</th>
   <th>Type</th>
   <th>Description</th>
  </tr>
  <tr>
   <td><code>cx</code></td>
   <td><!-- {{jsapixref("JSRuntime", "JSContext *")}} --></td>
   <td>The context in which the exception was thrown. <!-- {{ Jsapi-requires-request() }} --></td>
  </tr>
 </tbody>
</table>
<h2 id="Description" name="Description">Description</h2>
<p><code>JS_ClearPendingException</code> cancels the currently pending exception in <code>cx</code>, if any. (There is a pending exception if the most recently thrown exception in <code>cx</code> has not yet been caught or cleared.)</p>
<p>When any JSAPI call fails with an exception, the caller must either use <code>JS_ClearPendingException</code> to catch the exception; or return <code>false</code> to allow the exception to propagate to the caller.</p>
<p>Note that a JSAPI failure does not necessarily indicate that an exception is pending. Many JSAPI functions can simply report an error and return <code>false</code> <em>without</em> building and throwing an exception object. Use <!-- {{jsapixref("JS_IsExceptionPending")}} --> or <!-- {{jsapixref("JS_GetPendingException")}} --> to check for a pending exception.</p>
<p>See examples in the <a href="/En/SpiderMonkey/JSAPI_Phrasebook#Exception_handling" title="en/JSAPI_Phrasebook#Exception_handling">JSAPI Phrasebook</a>.</p>
<h2 id="See_Also" name="See_Also">See Also</h2>
<ul>
  <li><!-- {{ LXRSearch("ident", "i", "JS_ClearPendingException") }} --></li>
<li><!-- {{jsapixref("JS_GetPendingException")}} --></li>
<li><!-- {{jsapixref("JS_IsExceptionPending")}} --></li>
<li><!-- {{jsapixref("JS_ReportPendingException")}} --></li>
<li><!-- {{jsapixref("JS_SetPendingException")}} --></li>
</ul>